### PR TITLE
Added Openssl-dev dependicies

### PR DESCRIPTION
**Pull request by miry**
Strongswan require `crypto` library to be installed.

### CODE REVIEW

**Comment by myoung34** [comment]
👍

**Comment by fulldecent** [comment]
This fixes #33

**Review by fulldecent — APPROVED** [review]
Confirmed working OpenVZ/CentOS from FranTech buyvm.net

**Comment by kitten** [comment]
Sorry for not merging this for a long time ;) Kind of busy and I haven't put anything in place yet to test this repo quickly

**Pull request merged**
